<a href="https://colab.research.google.com/github/4cekay/B101-Group2-NLP-Project/blob/main/DatasetCuration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Setup**

In [1]:
!pip install numpy datasets

Requirement already satisfied: numpy in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.4.6)
Requirement already satisfied: datasets in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (5.0.0)
Requirement already satisfied: filelock in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from datasets) (3.29.5)
Requirement already satisfied: pyarrow>=21.0.0 in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from datasets) (25.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from datasets) (3.0.3)
Requirement already satisfied: requests>=2.32.2 in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from datasets) (2.34.2)
Requirement already satisfied: httpx<1.0.0 in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from datasets) (3.8.1)
Requirement already satisfied: multiprocess<0.70.20 in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.4.0,>=2023.1.0 in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2026.4.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from datasets) (1.23.0)
Requirement already satisfied: packaging in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (3.14.3)
Requirement already satisfied: anyio in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from httpx<1.0.0->datasets) (4.13.0)
Requirement already satisfied: certifi in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from httpx<1.0.0->datasets) (2026.4.22)
Requirement already satisfied: httpcore==1.* in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from httpx<1.0.0->datasets) (3.15)
Requirement already satisfied: h11>=0.16 in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.5.2)
Requirement already satisfied: typing-extensions>=4.1.0 in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Requirement already satisfied: colorama in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from click<9.0.0,>=8.4.2->huggingface-hub<2.0,>=0.25.0->datasets) (0.4.6)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.24.5)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests>=2.32.2->datasets) (2.7.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas->datasets) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\kacey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [2]:
import pandas as pd
import glob
import re
from datasets import load_dataset

**Helper #1:** cleaning formatted text (particularly for generated articles):

- Escaped strings
- Special tokens
- Formatting, markdown
- Metadata
- Placeholders
- Footers, promotional plugs

In [3]:
def clean_article(text, max_words=250):
  """
  Cleans article text blocks by removing all noisy instances listed below, and keeping derived sample within max word count.
  """
  if not text:
    return ""

  # if applicable, handle ALL instances of the following:

  # Escaped Strings
  text = text.replace("\\n", "\n")

  # Special Token (i.e. gemma's <end_of_turn>)
  text = re.sub(r"<end_of_turn>", "", text)

  # Formatting
  text = re.sub(r"^\s*#+\s*", "", text, flags=re.MULTILINE)         # header hashes
  text = re.sub(r"\*\*(.*?)\*\*", r"\1", text)                      # bold asterisks
  text = re.sub(r"^\s[\*\-]\s*", "", text, flags=re.MULTILINE)      # bullet points
  text = re.sub(r"^\s*[-*_]{3,}\s*$", "", text, flags=re.MULTILINE) # dividers

  # Metadata
  text = re.sub(r"^\s*(?:#+|\*\*)*\s*title\s*(?:\*\*)?\s*:\s*", "", text, flags=re.IGNORECASE | re.MULTILINE)       # "Title:"
  text = re.sub(r"^\s*(?:#+|\*\*)*\s*by\b.*$", "", text, flags=re.IGNORECASE | re.MULTILINE)                         # "by" writer
  text = re.sub(r"^\s(?:#+|\*\*)*\s*(?:published|date|author)\s*:.*$", "", text, flags=re.IGNORECASE | re.MULTILINE) # publication details
  text = re.sub(r"^\s*(?:#+|\*\*)*\s*background context\s*|(?:\*\*)?\s*:\s*", "", text, flags=re.IGNORECASE | re.MULTILINE)  # "Background Context"


  # Placeholders
  text = re.sub(r"\[\s*(?:insert|your|author|date|link|chart|image)[^\]]*\]", "", text, flags=re.IGNORECASE)

  # Footers
  text = re.sub(r"^\s*(?:#+|\*\*)*\s*(?:published|date|author)\s*:.*$", "", text, flags=re.IGNORECASE | re.MULTILINE)

  # keep # of paragraphs sampled within the word count (split by \n\n)
  paragraphs = [p.strip() for p in re.split(r'\n\s*\n+', text) if p.strip()]
  kept_paragraphs = []
  total_word_count = 0

  for p in paragraphs: # check each paragraph to make sure sample stays within max
    para_word_count = len(p.split())

    if total_word_count + para_word_count <= max_words:
      kept_paragraphs.append(p)
      total_word_count += para_word_count
    else:
      break

  # If the first paragraph is already too long, just don't use the sample
  if not kept_paragraphs:
    return None

  return "\n\n".join(kept_paragraphs)

In [24]:
def clean_CNN(text, max_words=250):
  """
  A revised version of the above function to clean CNN articles ALREADY IN THE SPLIT that are massive noisy blocks of tags, pain, and suffering.
  Attempts to truncate by paragraph, but with the length of some article blocks, sentence-trimming below word count might be necessary.
  """
  if not text:
    return ""

  # Escaped Strings
  text = text.replace("\\n", "\n")

  # Links, Embeds, Labels, etc.
  text = re.sub(r"Follow @\w+", "", text)
  text = re.sub(r"\bRead More\b", "", text, flags=re.IGNORECASE)
  text = re.sub(r"JUST WATCHED.*?Replay", "", text, flags=re.IGNORECASE | re.DOTALL)
  text = re.sub(r"More Videos\s*\.\.\.", "", text, flags=re.IGNORECASE)
  text = re.sub(r"MUST WATCH.*?\d{2}:\d{2}", "", text, flags=re.IGNORECASE | re.DOTALL)
  text = re.sub(r"Visit CNN\.com.*?videos", "", text, flags=re.IGNORECASE | re.DOTALL)

  # Twitter Embeds
  text = re.sub(r"pic\.twitter\.com/\S+", "", text)
  text = re.sub(r"#\w+", "", text)
  text = re.sub(r"[—\-]?\s*[\w\s]+?\(@\w+\)\s*\w+\s*\d{1,2},?\s*\d{4}", "", text)

  # Resulting Whitespace (if any)
  text = re.sub(r"[ \t]+", " ", text).strip()
  text = re.sub(r"\n{3,}", "\n\n", text)

  paragraphs = [p.strip() for p in re.split(r'\n\s*\n+', text) if p.strip()]
  kept_paragraphs = []
  total_word_count = 0

  for p in paragraphs:
    para_words = p.split()
    para_word_count = len(para_words)

    if total_word_count + para_word_count <= max_words:
      kept_paragraphs.append(p)
      total_word_count += para_word_count
    else: # specifically fits sentences within word count to avoid complete removal of samples with long first paragraphs.
      remaining_space = max_words - total_word_count

      if remaining_space > 0:
        truncated_words = para_words[:remaining_space]
        truncated = " ".join(truncated_words)

        last_punc = max( # check for last sentence-ender
            truncated.rfind("."),
            truncated.rfind("!"),
            truncated.rfind("?"),
        )
        # in the case of a long first paragraph with a running sentence, avoid cutting too much.
        if last_punc > len(truncated) * 0.7:
          truncated = truncated[:last_punc + 1]

        kept_paragraphs.append(truncated)
        total_word_count += remaining_space
      break

  # just in case, but hopefully all samples in final set have SOMETHING readable...?
  if not kept_paragraphs:
    return None

  return "\n\n".join(kept_paragraphs)

**Helper #2:** Gathering test/val split from a random subset of a chosen size

In [5]:
def split_subset(samples, subset_size, min_words, max_words, train_split=0.8, column="sample_text"):
  """
  Custom train/val subset splitter that will filter out unviable samples (out of word count range)
  """

  if samples is None or len(samples) ==0:
    return pd.DataFrame(), pd.DataFrame()

  # subset of random samples within set
  subset = (
      samples
      .filter(lambda example: min_words <= len(example[column].split()) <= max_words)
      .shuffle(seed=42)
      .select(range(subset_size))
  )

  # subset to dataframe + clear \n
  df_subset = subset.to_pandas()
  df_subset[column] =  df_subset[column].str.replace(r'[\r\n]+', " ", regex=True).str.strip()

  # split subset into train and val
  n_train = round(len(df_subset) * train_split) # number of training samples

  df_subset_train = df_subset.sample(n=n_train, random_state=42) # get train samples
  df_subset_val = df_subset.drop(df_subset_train.index)          # remove train samples to get val remainder


  return df_subset_train.reset_index(drop=True), df_subset_val.reset_index(drop=True)

# **Extraction**
[HF Dataset Processing](https://huggingface.co/docs/datasets/v1.4.0/processing.html)

## Email Replies

### Human-written

**Stanford Humanual-Email Dataset**

Columns:
- **completion:** ground-truth email reply
  - Main target text sample !!
- post_id (discard)
- user_id (discard)
- timestamp (discard)
- turn_id (discard)
  - Note: In conversation "turn 1" rows, I can take the original email content to use as a prompt for AI-generated samples to compare (w/ proper attribution)
- persona (discard)
- **prompt:** role and content
  - Will pull the initial email content of select conversations to use in prompting later.  
- metadata (discard)

In [ ]:
# Load the raw dataset (https://huggingface.co/datasets/snap-stanford/humanual-email)

raw_dataset = load_dataset('snap-stanford/humanual-email')
raw_dataset

README.md:   0%|          | 0.00/2.71k [00:00<?, ?B/s]

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 15.6MB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

data/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B /  675kB

data/test-00000-of-00001.parquet: downloading bytes:           |  0.00B

data/val-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B /  230kB

data/val-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/6377 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/536 [00:00<?, ? examples/s]

Generating val split:   0%|          | 0/130 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['completion', 'post_id', 'user_id', 'timestamp', 'turn_id', 'persona', 'prompt', 'metadata'],
        num_rows: 6377
    })
    test: Dataset({
        features: ['completion', 'post_id', 'user_id', 'timestamp', 'turn_id', 'persona', 'prompt', 'metadata'],
        num_rows: 536
    })
    val: Dataset({
        features: ['completion', 'post_id', 'user_id', 'timestamp', 'turn_id', 'persona', 'prompt', 'metadata'],
        num_rows: 130
    })
})

1. I'm gonna extract the initial email content of each conversation thread to use as prompts for our generative email samples later.

In [ ]:
# extracting only the rows with turn_id == 1, indicating the first "turn" in a round of emails

initial_emails = raw_dataset.filter(lambda example: example["turn_id"] == 1)

Filter:   0%|          | 0/6377 [00:00<?, ? examples/s]

Filter:   0%|          | 0/536 [00:00<?, ? examples/s]

Filter:   0%|          | 0/130 [00:00<?, ? examples/s]

In [ ]:
# removing all unwanted features, keeping only the "completion" and "prompt"
initial_emails = initial_emails.remove_columns(["post_id", "user_id", "timestamp", "turn_id", "persona", "metadata"])

2. Now, we take the actual email replies to use as training data.

In [ ]:
email_replies = initial_emails.map(
    lambda example: {
        "sample_replies": example["completion"].strip('\'"')
    },
    remove_columns= ["prompt", "completion"]
)

Map:   0%|          | 0/3780 [00:00<?, ? examples/s]

Map:   0%|          | 0/371 [00:00<?, ? examples/s]

Map:   0%|          | 0/96 [00:00<?, ? examples/s]

3. Take 900 samples from the train set that are within the word count range.

In [ ]:
max_words = 250
min_words = 20
sample_count = 900

email_replies_subset = (
    email_replies["train"]
    .filter(lambda example: min_words <= len(example["sample_replies"].split()) <= max_words)
    .shuffle(seed=42) # maintain same samples in notebook
    .select(range(sample_count))
)

Filter:   0%|          | 0/3780 [00:00<?, ? examples/s]

In [ ]:
email_replies_subset

Dataset({
    features: ['sample_replies'],
    num_rows: 900
})

In [ ]:
df_email_replies = email_replies_subset.to_pandas()
print(len(email_replies_subset))

df_email_replies

900

                                        sample_replies
0    Louise,\n\nWe are happy to do this.\n\nShall w...
1    Per Pam, the person we should be talking to is...
2    Louise,\n\nAttached is the list of Top 50 coun...
3    Sounds great. Just check with Audrey (3-5849) ...
4    Sally\n\nProposed list - of all potential cand...
..                                                 ...
895  Sorry about my incomplete memo (I hit send ins...
896  I'm a bit confused - I think that the current ...
897  Please see the three tabs for EGS and complete...
898  I maybe mistaken but I think Jack had given me...
899  i might go out.  i don't think that i am dress...

[900 rows x 1 columns]

In [ ]:
# index=False to get rid of the index no. column

df_email_replies.to_csv('human_email_samples.csv', index=False)

### AI-generated

Gathering the context (prompt --> content) for a number of email replies (completion) in the dataset.
These will be fed into different generative AI models, asking for an appropriate response.

In [ ]:
# extract the email content from each prompt,
# get rid of quotation marks from the beginning and end
# remove the old columns
email_prompts = initial_emails.map(
    lambda example: {
        "text": example["prompt"][0]["content"].strip('\'"') # get rid of quotes
    },
    remove_columns= ["completion", "prompt"]
)

Map:   0%|          | 0/3780 [00:00<?, ? examples/s]

Map:   0%|          | 0/371 [00:00<?, ? examples/s]

Map:   0%|          | 0/96 [00:00<?, ? examples/s]

In [ ]:
max_words = 250
min_words = 20
sample_count = 225

email_prompts_subset = (
    email_prompts["train"]
    .filter(lambda example: min_words <= len(example["text"].split()) <= max_words)
    .shuffle(seed=42) # maintain same samples in notebook
    .select(range(sample_count))
)

Filter:   0%|          | 0/3780 [00:00<?, ? examples/s]

In [ ]:
df_email_prompts = email_prompts_subset.to_pandas()

df_email_prompts

                                                  text
0    The Ninth Circuit Court of Appeals has schedul...
1    Ken Lay spoke with several California CEOs thi...
2    TJ,\n\nThe following Realtime employees on the...
3    Revised Trading Policy.  We would like to get ...
4    Legal -\n\nAttached below is an Omnibus Confir...
..                                                 ...
220  Chris,\n\nJust wanted to verify a portion of s...
221  The issue of O&M fees at new interconnects has...
222  Daren - meter 1517 has a nom of 0/day for Jan....
223  There are about 20-30 deals in pending sent to...
224  PLEASE MARK YOUR CALENDAR:\n\nThe Moody's Valu...

[225 rows x 1 columns]

In [ ]:
# csv export example (index=False to get rid of the index no. column)

df_email_prompts.to_csv('human_email_prompts.csv', index=False)

AI-Generated Replies to each prompt email:

Prompt: Can you reply (within 250 words) to each of the 225 emails attached in an appropriate, professional manner?

Export to a csv file with one sample_text column with replies.

[Attached human_email_prompts.csv]

In [ ]:
# splitting the bigger csv into halves for agents (gemini)

email_prompts_1, email_prompts_2 = split_subset(email_prompts_subset, 225, 20, 250, train_split=0.5, column="text")

print(email_prompts_1)
print(email_prompts_2)

Filter:   0%|          | 0/225 [00:00<?, ? examples/s]

                                                  text
0    Mike:  Attached is a spreadsheet that summariz...
1    We apologize about the error in the previous e...
2    True Orange E-Mail/Fax Service Volume 9, E-Mai...
3    Sharon - I need your assistance with respect t...
4    In January 2001, Transwestern had $127,750 rev...
..                                                 ...
107  Ken Lay spoke with several California CEOs thi...
108  Tracy, As you know Project Sunrise no longer h...
109  Phillip, I have attached a list of the Common ...
110  Just found out that we have acces to 15,000 of...
111  Apologies for the late notice!  Please remove ...

[112 rows x 1 columns]
                                                  text
0    Greetings.  Hope, given the circumstances, tha...
1    Revised Trading Policy.  We would like to get ...
2    Rod and Joe, Here is a proposed write up of th...
3    Quck question:  w.r.t. to the stipulation with...
4    Leslie, I just spoke with the gas futures trad...
..                                                 ...
108  Jeff, I am an Enron Wholesale Services attorne...
109  Cautiously optimistic. Jordan and I are still ...
110  Dave, thanks for the note. Regarding an update...
111  Today FOEX published its index for NBSK and BH...
112  Please note the following addition to the EPMI...

[113 rows x 1 columns]

In [ ]:
email_prompts_1.to_csv("human_email_prompts_112", index=False)
email_prompts_2.to_csv("human_email_prompts_113", index=False)

In [ ]:
from datasets import Dataset

# even smaller splits (copilot)

email_prompts_half_1 = Dataset.from_pandas(email_prompts_1)
email_prompts_half_2 = Dataset.from_pandas(email_prompts_2)

email_prompts_11, email_prompts_12 = split_subset(email_prompts_half_1, 112, 20, 250, train_split=0.5, column="text")
email_prompts_21, email_prompts_22 = split_subset(email_prompts_half_2, 112, 20, 250, train_split=0.5, column="text")

print(email_prompts_11)
print(email_prompts_12)
print(email_prompts_21)
print(email_prompts_22)

Filter:   0%|          | 0/112 [00:00<?, ? examples/s]

Filter:   0%|          | 0/113 [00:00<?, ? examples/s]

                                                 text
0   Columbia Gas Transmission Corporation has in i...
1   Andy: \tI am in the process of revising my for...
2   FIT1 for AR_AP and Earnings products completed...
3   Legal has been asked to review and approve all...
4   Carrie \tMr. Colin Wilkes from General Electri...
5   Michael Moran, currently Managing Director and...
6   Chris, Just wanted to verify a portion of sita...
7   True Orange E-Mail/Fax Service Volume 9, E-Mai...
8   Louise, Attached is a new table derived from t...
9   Darron - Thanks for your continued help with t...
10  Phillip,        I received a fax of the consen...
11  We apologize about the error in the previous e...
12  EFFECTS ON DISTRIBUTED ENERGY ARE UNCLEAR On S...
13  Billy: I hope all is well.  Per our discussion...
14  We will hold off transferring any physical pos...
15  As discussed these individuals will transfer t...
16  John, per your request price for front and bac...
17  I want to let you all know that we have reache...
18  Yesterday we noticed a problem where reports w...
19  Daren - meter 1517 has a nom of 0/day for Jan....
20  Steve: You had requested that we get the Rice ...
21  Bob,  The following production is now on-line ...
22  I have a price discrepancy with one of Stacey'...
23  Kevin: Per you request I left a phone message ...
24  We plan to have a conference call at 2pm Sunda...
25  Louise, please review and if you require more ...
26  Apologies for the late notice!  Please remove ...
27  All, Just wanted to touch base with you to see...
28  Put a bid into SOCO's shareholders for the tra...
29  Starting on Thursday,  April 19, at 2:00 p.m. ...
30  * CERA's revised oil demand forecast is for a ...
31  Aimee: Following is a list of allocation excep...
32  Greg Whalley's four diamond club level Astros ...
33  Dear Vince, Greetings from NY & hope all is we...
34  The African American caucus would like to have...
35  We have a 90,000 MMBtu/d first of the month no...
36  Energy conservation efforts leave California b...
37  Louise & Tammie, I want to thank you for the b...
38  Sam & Stephanie, Re:  Cargill Ferrous Internat...
39  Attached please find the revised GTV II Phase ...
40  PLEASE MARK YOUR CALENDAR Date:   Every Thursd...
41  Let me clarify a point about the Performance E...
42  Tracy, As you know Project Sunrise no longer h...
43  Kevin, I have worked with this guy at EBS for ...
44  Attention Taliban! You are condemned. Did you ...
45  Hi Michelle; Dovie told me that she has had a ...
46  my predicament at running back will last me on...
47  Sam, I appreciate your point.  Apparently, the...
48  Attached are the comments of CFACTS on the con...
49  For once his is not a Panenergy question.  For...
50  I was out of town last week on vacation.  The ...
51  Legal Team-- ONEOK Energy Marketing and Tradin...
52  In preparation for Friday's Bank Conference, C...
53  Hi All,  Attached is the OPM Monthly Hours Sur...
54  Just found out that we have acces to 15,000 of...
55  Those of you that are concerned about the chan...
                                                 text
0   Mike:  Attached is a spreadsheet that summariz...
1   I would like to see a first draft of the 2001 ...
2   Dear Vince Just a quick message to follow up o...
3   Okay, not sure who, if anyone, cares or needs ...
4   I will not be able to be at the meeting today....
5   The dictionary says that malt is "Grain, usual...
6   Dear Vince and Stinson, Today I announced my r...
7   Chris, Someone here said that letters were pas...
8   Sally,  Attached is the updated of the headcou...
9   Would each of you send me a copy of your credi...
10  The attached spreadsheet outlines the rotation...
11  Thanks againg for sharing your thoughts and op...
12  In January 2001, Transwestern had $127,750 rev...
13  I have 4 tickets for the Astros game on Thursd...
14  Due to a Cogen shut down  September 25 - 30th,...
15  Mary - here is a draft of what the PGE interco...
16  Vince:  Just wondering if you had any informat...
17  Lets make sure we are picking-up on the other ...
18  Hi Harry, Hope you had a good trip to New York...
19  Morning, Glory, Hope you are doing well and ha...
20  Enron Corp. is set to replace CFO Andrew Fasto...
21  Mr. Dasovich, Hello, my name is Adam, and I wo...
22  Tana, I have picked up the Dynegy Direct contr...
23  Hi Joann and Alvin, As you know, effective Oct...
24  In discussions with several agency personnel, ...
25  Lynn and Steve, How hard would it be for someo...
26  Phillip, I have attached a list of the Common ...
27  Sharon - I need your assistance with respect t...
28  Market Participants: Attached please find a no...
29  Louise: I have given to your admin a copy of t...
30  I have received the settlement agreement back ...
31  Ken Lay spoke with several California CEOs thi...
32  Sally, This is the communication summary we di...
33  Please fill in the training and/or development...
34  The Commercial Group has asked whether they ca...
35  Sharon: Does ECC have any physical gas masters...
36  TJ, The following Realtime employees on the Ea...
37  Hi Jim, As I mentioned in the elevator last we...
38  Vince- Are you guys still working on that "pro...
39  What if we could contract with Agave under the...
40  All,   Annette Harris wishes to put new produc...
41  Vince, Wade was in town today and I caught him...
42  Dear Team, In the next couple of weeks, I will...
43  Robert: I have not yet received data from Stev...
44  Ettera issues: 1.  When hourly is asked to man...
45  Here is a quick and dirty worksheet.  I've bee...
46  Hi Vince, I am writing you at this time to inq...
47  Tried each of your numbers and pager this morn...
48  PLEASE MARK YOUR CALENDAR: The Moody's Value A...
49  Dear Sir or Madam, Carolina Power & Light Comp...
50  Mr. Kaminski, Your reference to Mr. Akerlof's ...
51  Jeff, this Agreement should replace the GISB a...
52  I am faxing to each of you a copy of a letter ...
53  Hi Monika, Here is your file.  Again, I could ...
54  Here is the updated memo.  You might have some...
55  Dear Dr. Kaminski, I would appreciate if you c...
                                                 text
0   Marnie - I think I need to take a half day of ...
1   Sorry for the late notice, but is it possible ...
2   Shelley & Lynn,   Fran has advised me there ar...
3   John,  I am not sure if I have already sent yo...
4   Any more progress on the Management Conference...
5   Tana - The legal name is: Brent Broker.com LLC...
6   True Orange E-Mail/Fax Service Volume 9, E-Mai...
7   I will be giving a training session on Wed   9...
8   Hi Bob: Could you please leave on my voicemail...
9   Kim, Hope all is well at the big "E" these day...
10  Great Lakes is now e:mailing their daily confi...
11  Kerry, As you are probably aware, the EES Risk...
12  Rick and Lynn, I just wanted to give you an of...
13  Please respond to Mr. Campbell, Based on the r...
14  Is this guy new?  He is in none of my HR files...
15  This e-mail is to follow up our conversation F...
16  Hi Rick, I'm in the process of planning the U....
17  Attached is the latest version of the cost cen...
18  Phillip; I see that you talked to Andrew this ...
19  I have 4 astro tickets forTuesday, July 17 (As...
20  Dear Vince, Greetings from NY and hope that al...
21  As a follow up to our discussion earlier this ...
22  LeShawn Edwards, currently a contractor in Ela...
23  Attached in Word format are the draft IEP comm...
24  Today FOEX published its index for NBSK and BH...
25  Quck question:  w.r.t. to the stipulation with...
26  I know I owe you some names and phone numbers....
27  Legal - Attached below is an Omnibus Confirm w...
28  whatup beeatch . . . are you definitely gonna ...
29  Please plan to attend a meeting , Friday, Octo...
30  Rod and Joe, Here is a proposed write up of th...
31  quick question....which report in RISI do i lo...
32  Tara and Melba, Tori Kuykendahl would like to ...
33  Transco has called wanting to know who is resp...
34  What are you doing?  Wake up over there sexy. ...
35  In this third e-mail, I write you concerning t...
36  Could we please request 2 copies of your Trans...
37  I need to send this to Jeff and Ray and get it...
38  There are about 20-30 deals in pending sent to...
39  Please review and let me know if you would lik...
40  Legal Team-- Attached below is a credit worksh...
41  One of our potential buyers will be here at 9a...
42  Attached please find a schedule of planned all...
43  I had a chance to speak with Christian LeBroc ...
44  Dave, thanks for the note. Regarding an update...
45  Mike: We'd talked about getting together to di...
46  To all: The attached memo summarizes our discu...
47  Andrea, Please incoroporate these issues into ...
48  Jeff Just to inform that  the above project ha...
49  Per your request here are the documents you mi...
50  Robert Attached is a marketing project for an ...
51  Before you leave today or first thing in the m...
52  Leslie, I just spoke with the gas futures trad...
53  Tracy, Please update the rate case segment for...
54  Company name should be replaced by your busine...
55  I would like to have a planning meeting tomorr...
                                                 text
0   This is a reminder that the next Weekly Risk F...
1   Attached for your review and comment is a broa...
2   Greetings.  Hope, given the circumstances, tha...
3   Please Note: POI 1309 ( NNG Beaver) will start...
4   Vince, Pursuant to our conversation, I called ...
5   HR is requesting and updated Org Chart from Ti...
6   Hetco  and Enron have mutually agreed to cance...
7   This is CRAZY!!!  Looks like something straigh...
8   The issue of O&M fees at new interconnects has...
9   The time has finally come for us to mourn the ...
10  Attached are the latest versions of the SPA, l...
11  Please note the following addition to the EPMI...
12  Sally, The attached file shows the detail of p...
13  Doug, A few weeks back I showed you a picture ...
14  Phillip: Steve and I are inquiring on the emai...
15  At the request of Credit, we have developed a ...
16  Webb is the one most concerned. The talking po...
17  We have received the following executed financ...
18  Lynn and Rick:   In conjunction with getting f...
19  Ivonne Brown submitted your anniversary increa...
20  Attached please find draft papers for the appr...
21  we have the eol case today in Entrepreneurial ...
22  Hi Julie, I have a question and I wasn't sure ...
23  Steve,  Rick asked me to send you an email reg...
24  Ricki, Could you please send a package to my h...
25  Hi Janel: My name is Michelle Rafter and I'm a...
26  Revised Trading Policy.  We would like to get ...
27  Colleen, As I understand it, we were acting as...
28  Jeff / John, We have drafted a note relating t...
29  Dear Vince, Thank you for your prompt response...
30  sorry i missed this morning.  i was out of tow...
31  Please join us for a  Storage 101 Class schedu...
32  Jeff, I am an Enron Wholesale Services attorne...
33  Steve Good news.  As you indicated would happe...
34  The Ninth Circuit Court of Appeals has schedul...
35  Miss Tana, Is there a chance you might like to...
36  In order for Cadwalader to be in a position to...
37  Anne, Per our discussion this morning, attache...
38  As an FYI for those not already in the loop, n...
39  Mark, can you confirm that you approve these l...
40  Attached is the CERA paper on the economic imp...
41  The report named: West NG Basis Positions <htt...
42  The following topics were discussed at the mee...
43  Attention Logistics Managers!  Beginning in No...
44  I've allowed one person to enter Enron America...
45  Tana: Please prepare a bilateral NDA for the f...
46  Cautiously optimistic. Jordan and I are still ...
47  We currently have 2 park & loan deals with Col...
48  Lisa,      Breakfast sandwiches and coffee cou...
49  Jeff, My biggest concern is that we draw attan...
50  These physical CPs show up as live.  However m...
51  Vince, Czesc, Our group would like to recruit ...
52  Attached is a spreadsheet which tracks the CES...
53  Hi Greg, We created the database for them and ...
54  The next session to discuss papers on models f...
55  We are not giving any more money in California...

In [ ]:
email_prompts_11.to_csv("human_email_prompts_q1_56.csv", index=False)
email_prompts_12.to_csv("human_email_prompts_q2_56.csv", index=False)
email_prompts_21.to_csv("human_email_prompts_q3_56.csv", index=False)
email_prompts_22.to_csv("human_email_prompts_q4_56.csv", index=False)

In [ ]:
email_prompts_21['text'][28]

"whatup beeatch . . . are you definitely gonna go out thurs nite . . . i'm goin out with a chick sometime this week/weekend but haven't decided which nite . . . when are you taking that hot physical therapist out ?"

In [ ]:
path = r"C:\Users\kacey\OneDrive\IAT360\NLP_Project\generated_samples\*.csv"
ai_samples_csv = glob.glob(path)

ai_email_train = []
ai_email_val = []

for file in ai_samples_csv:
  df = pd.read_csv(file)

  # 5 random rows
  val_sample = df.sample(n=5, random_state=42)
  ai_email_val.append(val_sample)

  # rest to training
  train_sample = df.drop(val_sample.index)
  ai_email_train.append(train_sample)

# concat
df_ai_email_train = pd.concat(ai_email_train, ignore_index=True)
df_ai_email_val = pd.concat(ai_email_val, ignore_index=True)

# save to their own csv file
df_ai_email_train.to_csv('train_ai_email_samples.csv', index=False)
df_ai_email_val.to_csv('val_ai_email_samples.csv', index=False)

print(f"Validation rows: {len(df_ai_email_val)}")
print(f"Training rows: {len(df_ai_email_train)}")

Validation rows: 20
Training rows: 80

In [ ]:
path_112 = r"C:\Users\kacey\OneDrive - Simon Fraser University (1sfu)\IAT360\NLP Project\gemini\gemini_cleaned_1.csv"
path_113 = r"C:\Users\kacey\OneDrive - Simon Fraser University (1sfu)\IAT360\NLP Project\gemini\gemini_cleaned_2.csv"


df_gemini_112 = pd.read_csv(path_112)
df_gemini_113 = pd.read_csv(path_113)

gemini = [df_gemini_112, df_gemini_113]

df_gemini_complete= pd.concat(gemini, ignore_index=True)

df_gemini_complete.to_csv("gemini_emails_225.csv", index=False)
print(len(df_gemini_complete))

225

In [ ]:
path = r"C:\Users\kacey\OneDrive - Simon Fraser University (1sfu)\IAT360\NLP Project\dataset\generated_samples\emails (by model)\225\*.csv"
ai_samples_csv = glob.glob(path)

ai_emails = []

for file in ai_samples_csv:
  df = pd.read_csv(file)
  ai_emails.append(df)

# concat
df_ai_emails = pd.concat(ai_emails, ignore_index=True)

# save to their own csv file
df_ai_emails.to_csv('ai_emails_900.csv', index=False)

print(len(df_ai_emails))

900

## Abstracts

### AI-generated

In [ ]:
# https://huggingface.co/datasets/Ateeqq/AI-and-Human-Generated-Text

raw_dataset = load_dataset('Ateeqq/AI-and-Human-Generated-Text')
raw_dataset

DatasetDict({
    train: Dataset({
        features: ['title', 'abstract', 'label'],
        num_rows: 22930
    })
    test: Dataset({
        features: ['title', 'abstract', 'label'],
        num_rows: 5732
    })
})

In [ ]:
# extracting only the AI-generated samples (label = 1)

initial_abstracts = raw_dataset.filter(lambda example: example["label"] == 1)

# removing all unwanted features, keeping only "abstract"
initial_abstracts = initial_abstracts.remove_columns(["title", "label"])

initial_abstracts

DatasetDict({
    train: Dataset({
        features: ['abstract'],
        num_rows: 11465
    })
    test: Dataset({
        features: ['abstract'],
        num_rows: 2866
    })
})

In [ ]:
max_words = 250
sample_count = 900

abstracts_subset = (
    initial_abstracts["train"]
    .filter(lambda example: len(example["abstract"].split()) <= max_words)
    .shuffle(seed=42) # maintain same samples in notebook
    .select(range(sample_count))
)

In [ ]:
df_abstracts = abstracts_subset.to_pandas()
df_abstracts =  df_abstracts.replace(r'\n+|\r+', ' ', regex=True)

print(len(abstracts_subset))

df_abstracts.to_csv('ai_abstracts_900.csv', index=False)

900

In [ ]:
df_abstracts

                                             abstract
0    This article presents a systematic review of ...
1    This paper introduces the practical steps for...
2    This study explores the novel use of isotherm...
3    This study explores the mechanism by which he...
4    This article explores the intersection of the...
..                                                ...
95    This study focuses on the incidence, predict...
96   This paper describes the successful developme...
97   This research article investigates the potent...
98   This paper explores the potential of in vitro...
99    This article reveals the results of a study ...

[100 rows x 1 columns]

In [ ]:
ai_abstract_train = []
ai_abstract_val = []

val_sample = df_abstracts.sample(n=20, random_state=42)
ai_abstract_val.append(val_sample)

train_sample = df_abstracts.drop(val_sample.index)
ai_abstract_train.append(train_sample)

# concat into dataframes for each split
df_ai_abstract_train = pd.concat(ai_abstract_train, ignore_index=True)
df_ai_abstract_val = pd.concat(ai_abstract_val, ignore_index=True)

# save to their own csv file
df_ai_abstract_train.to_csv('train_ai_abstract_samples.csv', index=False)
df_ai_abstract_val.to_csv('val_ai_abstract_samples.csv', index=False)

print(f"Validation rows: {len(df_ai_abstract_val)}")
print(f"Training rows: {len(df_ai_abstract_train)}")

Validation rows: 20
Training rows: 80

## News Articles

### AI-generated

In [6]:
# https://huggingface.co/datasets/gsingh1-py/train

raw_dataset = load_dataset('gsingh1-py/train')
raw_dataset

Repo card metadata block was not found. Setting CardData to empty.

DatasetDict({
    train: Dataset({
        features: ['prompt', 'Human_story', 'gemma-2-9b', 'mistral-7B', 'qwen-2-72B', 'llama-8B', 'accounts/yi-01-ai/models/yi-large', 'GPT_4-o'],
        num_rows: 7321
    })
})

In [7]:
# extracting and cleaning from each model's samples

model_columns = ["gemma-2-9b", "qwen-2-72B", "llama-8B", "GPT_4-o" ]

cleaned_datasets = {}

for model in model_columns:
  if model in raw_dataset["train"].column_names:
    cleaned_datasets[model] = (
        raw_dataset.map(
            lambda example: {"sample_text": clean_article(example[model])},
            remove_columns=raw_dataset["train"].column_names
        ) # filter out the blanks (cleared out after not fitting in word count)
        .filter(lambda example: example["sample_text"] is not None and len(example["sample_text"].strip()) > 0)
    )

Map:   0%|          | 0/7321 [00:00<?, ? examples/s]

Filter:   0%|          | 0/7321 [00:00<?, ? examples/s]

Map:   0%|          | 0/7321 [00:00<?, ? examples/s]

Filter:   0%|          | 0/7321 [00:00<?, ? examples/s]

Map:   0%|          | 0/7321 [00:00<?, ? examples/s]

Filter:   0%|          | 0/7321 [00:00<?, ? examples/s]

Map:   0%|          | 0/7321 [00:00<?, ? examples/s]

Filter:   0%|          | 0/7321 [00:00<?, ? examples/s]

In [9]:
cleaned_datasets

{'gemma-2-9b': DatasetDict({
     train: Dataset({
         features: ['sample_text'],
         num_rows: 7310
     })
 }),
 'qwen-2-72B': DatasetDict({
     train: Dataset({
         features: ['sample_text'],
         num_rows: 5683
     })
 }),
 'llama-8B': DatasetDict({
     train: Dataset({
         features: ['sample_text'],
         num_rows: 7306
     })
 }),
 'GPT_4-o': DatasetDict({
     train: Dataset({
         features: ['sample_text'],
         num_rows: 7285
     })
 })}

In [10]:
gemma_articles = cleaned_datasets['gemma-2-9b']['train']
qwen_articles = cleaned_datasets['qwen-2-72B']['train']
llama_articles = cleaned_datasets['llama-8B']['train']
gpt_articles = cleaned_datasets['GPT_4-o']['train']

In [11]:
gemma_train_split, gemma_val_split = split_subset(gemma_articles, 225, 50, 250, train_split=1)
qwen_train_split, qwen_val_split = split_subset(qwen_articles, 225, 50, 250, train_split=1)
llama_train_split, llama_val_split = split_subset(llama_articles, 225, 50, 250, train_split=1)
gpt_train_split, gpt_val_split = split_subset(gpt_articles, 225, 50, 250, train_split=1)

Filter:   0%|          | 0/7310 [00:00<?, ? examples/s]

Filter:   0%|          | 0/5683 [00:00<?, ? examples/s]

Filter:   0%|          | 0/7306 [00:00<?, ? examples/s]

Filter:   0%|          | 0/7285 [00:00<?, ? examples/s]

In [14]:
ai_articles_train = [gemma_train_split, qwen_train_split, llama_train_split, gpt_train_split]

# concat
df_ai_articles_train = pd.concat(ai_articles_train, ignore_index=True)

# save to their own csv file
df_ai_articles_train.to_csv('ai_articles_900.csv', index=False)

print(len(df_ai_articles_train))

900

# **Compilation**

## Training
 Set

In [ ]:
path = r"C:\Users\kacey\OneDrive\IAT360\NLP_Project\generated_samples\*.csv"
ai_samples_csv = glob.glob(path)

ai_email_train = []
ai_email_val = []

for file in ai_samples_csv:
  df = pd.read_csv(file)

  # 5 random rows
  val_sample = df.sample(n=5, random_state=42)
  ai_email_val.append(val_sample)

  # rest to training
  train_sample = df.drop(val_sample.index)
  ai_email_train.append(train_sample)

# concat
df_ai_email_train = pd.concat(ai_email_train, ignore_index=True)
df_ai_email_val = pd.concat(ai_email_val, ignore_index=True)

# save to their own csv file
df_ai_email_train.to_csv('train_ai_email_samples.csv', index=False)
df_ai_email_val.to_csv('val_ai_email_samples.csv', index=False)

print(f"Validation rows: {len(df_ai_email_val)}")
print(f"Training rows: {len(df_ai_email_train)}")

In [15]:
# load saved category subsets into dfs
df_ai_email_samples = pd.read_csv(r"C:\Users\kacey\OneDrive - Simon Fraser University (1sfu)\IAT360\NLP Project\dataset\generated_samples\per category (900)\ai_emails_900.csv")
df_ai_abstract_samples = pd.read_csv(r"C:\Users\kacey\OneDrive - Simon Fraser University (1sfu)\IAT360\NLP Project\dataset\generated_samples\per category (900)\ai_abstracts_900.csv")
df_ai_article_samples = pd.read_csv(r"C:\Users\kacey\OneDrive - Simon Fraser University (1sfu)\IAT360\NLP Project\dataset\generated_samples\per category (900)\ai_articles_900.csv")

# add sub-type labels before compilation
df_ai_email_samples["sub-type"] = "email"
df_ai_abstract_samples["sub-type"] = "abstracts"
df_ai_article_samples["sub-type"] = "news"

# concat into one set and add their AI label (these ones are all generated samples)
ai_formal_samples=[df_ai_email_samples, df_ai_abstract_samples, df_ai_article_samples]

df_ai_formal_samples =  pd.concat(ai_formal_samples, ignore_index=True)
df_ai_formal_samples["AI_label"] = 1

# export to csv
df_ai_formal_samples.to_csv("ai_formal_samples_2700.csv", index=False)

In [35]:
# load saved category subsets into dfs
df_human_email_samples = pd.read_csv(r"C:\Users\kacey\OneDrive - Simon Fraser University (1sfu)\IAT360\NLP Project\dataset\written_samples\human_emails_900.csv")
df_human_abstract_samples = pd.read_csv(r"C:\Users\kacey\OneDrive - Simon Fraser University (1sfu)\IAT360\NLP Project\dataset\written_samples\human_abstracts_900.csv")
df_human_article_samples = pd.read_csv(r"C:\Users\kacey\OneDrive - Simon Fraser University (1sfu)\IAT360\NLP Project\dataset\written_samples\human_articles_900.csv")

# add sub-type + AI label if needed
df_human_email_samples["sub-type"] = "email"
df_human_email_samples["AI_label"] = 0

# concat
human_formal_samples=[df_human_email_samples, df_human_abstract_samples, df_human_article_samples]
df_human_formal_samples =  pd.concat(human_formal_samples, ignore_index=True)

# export to csv
df_human_formal_samples.to_csv("human_formal_samples_2700.csv", index=False)

In [36]:
h_path = r"C:\Users\kacey\OneDrive - Simon Fraser University (1sfu)\IAT360\NLP Project\dataset\per class (2700)\human_formal_samples_2700.csv"
h_df = pd.read_csv(h_path)

ai_path = r"C:\Users\kacey\OneDrive - Simon Fraser University (1sfu)\IAT360\NLP Project\dataset\per class (2700)\ai_formal_samples_2700.csv"
ai_df = pd.read_csv(ai_path)

df_dataset = pd.concat([h_df, ai_df], ignore_index=True)
print(df_dataset)

df_dataset.to_csv("formal_dataset_5400.csv", index=False)

                                            sample_text sub-type  AI_label
0     Louise,\n\nWe are happy to do this.\n\nShall w...    email         0
1     Per Pam, the person we should be talking to is...    email         0
2     Louise,\n\nAttached is the list of Top 50 coun...    email         0
3     Sounds great. Just check with Audrey (3-5849) ...    email         0
4     Sally\n\nProposed list - of all potential cand...    email         0
...                                                 ...      ...       ...
5395  A Moment of UnitySanders and Biden Discuss Key...     news         1
5396  In Defense of WineRediscovering the Timeless E...     news         1
5397  HeadlineCruz Courts Establishment Support on T...     news         1
5398  Protesters Will Call for Higher Wages and Unio...     news         1
5399  City University of New York Faces Criticism fo...     news         1

[5400 rows x 3 columns]

## Validation Set

### AI-generated

In [37]:
# Load the raw dataset (https://huggingface.co/datasets/artfultom/ivypanda-llm-generated-essays)

raw_dataset = load_dataset('artfultom/ivypanda-llm-generated-essays', 'one prompt')
raw_dataset

DatasetDict({
    train: Dataset({
        features: ['title', 'prompt', 'text', 'model'],
        num_rows: 22492
    })
})

In [38]:
mistral_essays = raw_dataset.filter(lambda example: example["model"] == "mistral-7b-instruct-v0.2.Q5_K_M")
llama_essays = raw_dataset.filter(lambda example: example["model"] == "llama-3-13B-Instruct-v0.1.Q5_K_M")
deepseek_essays = raw_dataset.filter(lambda example: example["model"] == "deepseek-chat")

In [39]:
mistral_cleaned = (
    mistral_essays.map(
            lambda example: {"sample_text": clean_article(example["text"])},
            remove_columns=mistral_essays["train"].column_names
        ) # filter out the blanks (cleared out after not fitting in word count)
        .filter(lambda example: example["sample_text"] is not None and len(example["sample_text"].strip()) > 0)
    )

llama_cleaned = (
    llama_essays.map(
            lambda example: {"sample_text": clean_article(example["text"])},
            remove_columns=llama_essays["train"].column_names
        ) # filter out the blanks (cleared out after not fitting in word count)
        .filter(lambda example: example["sample_text"] is not None and len(example["sample_text"].strip()) > 0)
    )

deepseek_cleaned = (
    deepseek_essays.map(
            lambda example: {"sample_text": clean_article(example["text"])},
            remove_columns=deepseek_essays["train"].column_names
        ) # filter out the blanks (cleared out after not fitting in word count)
        .filter(lambda example: example["sample_text"] is not None and len(example["sample_text"].strip()) > 0)
    )


# create subsets with select samples for validation

mistral_samples, blank = split_subset(mistral_cleaned['train'], 135, 50, 250, train_split=1)
llama_samples, blank = split_subset(llama_cleaned['train'], 135, 50, 250, train_split=1)
deepseek_samples, blank = split_subset(deepseek_cleaned['train'], 135, 50, 250, train_split=1)

Map:   0%|          | 0/4500 [00:00<?, ? examples/s]

Filter:   0%|          | 0/4500 [00:00<?, ? examples/s]

Map:   0%|          | 0/2993 [00:00<?, ? examples/s]

Filter:   0%|          | 0/2993 [00:00<?, ? examples/s]

Map:   0%|          | 0/8999 [00:00<?, ? examples/s]

Filter:   0%|          | 0/8999 [00:00<?, ? examples/s]

Filter:   0%|          | 0/4495 [00:00<?, ? examples/s]

Filter:   0%|          | 0/2993 [00:00<?, ? examples/s]

Filter:   0%|          | 0/8685 [00:00<?, ? examples/s]

In [40]:
llm_essays = [mistral_samples, llama_samples, deepseek_samples]
df_llm_essays = pd.concat(llm_essays, ignore_index=True)

df_llm_essays["sub-type"] = "essay"
df_llm_essays

                                           sample_text sub-type
0    In the complex and intricate web of religious ...    essay
1    In DreamsSurrealism and the Human Condition Su...    essay
2    In the current societal discourse, vaccine man...    essay
3    Afghanistan, a landlocked country located at t...    essay
4    The field of behavior analysis has gained sign...    essay
..                                                 ...      ...
400  The assessment of personality represents a cor...    essay
401  The world of business is not a sterile laborat...    essay
402  The equitable and efficient distribution of va...    essay
403  The image of a nurse is often confined to the ...    essay
404  The structured discipline and strategic orient...    essay

[405 rows x 2 columns]

In [41]:
# path = r"C:\Users\kacey\OneDrive - Simon Fraser University (1sfu)\IAT360\NLP Project\dataset\validation\kimi-2.6\*.csv"
# kimi_samples_csv = glob.glob(path)

# kimi_samples = []

#for file in kimi_samples_csv:
  #df = pd.read_csv(file)
  #kimi_samples.append(df)

# concat
#df_kimi_samples= pd.concat(kimi_samples, ignore_index=True)
df_kimi_samples = pd.read_csv(r"C:\Users\kacey\OneDrive - Simon Fraser University (1sfu)\IAT360\NLP Project\dataset\validation\kimi_formal_samples_135.csv")

print(len(df_kimi_samples))

135

In [42]:
#path = r"C:\Users\kacey\OneDrive - Simon Fraser University (1sfu)\IAT360\NLP Project\dataset\validation\meta-AI\*.csv"
#metaAI_samples_csv = glob.glob(path)

#metaAI_samples = []

#for file in metaAI_samples_csv:
  #df = pd.read_csv(file)
  #metaAI_samples.append(df)

# concat
#df_metaAI_samples= pd.concat(metaAI_samples, ignore_index=True)
df_metaAI_samples = pd.read_csv(r"C:\Users\kacey\OneDrive - Simon Fraser University (1sfu)\IAT360\NLP Project\dataset\validation\metaAI_formal_samples_135.csv")


print(len(df_metaAI_samples))

135

In [43]:
kimi_subtypes = []

i=0
while i < 135:
  if 0 <= i <= 46:
    kimi_subtypes.append("nonfiction")
  elif 47 <= i <= 91:
    kimi_subtypes.append("business")
  else:
    kimi_subtypes.append("letter")
  i+= 1

metaAI_subtypes = []
i=0
while i < 135:
  if 0 <= i <= 46:
    metaAI_subtypes.append("business")
  elif 47 <= i <= 91:
    metaAI_subtypes.append("letter")
  else:
    metaAI_subtypes.append("nonfiction")
  i+= 1

print(kimi_subtypes)
print(metaAI_subtypes)

['nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter']
['business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'business', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'letter', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction', 'nonfiction']

In [44]:
df_kimi_samples["sub-type"] = kimi_subtypes
df_metaAI_samples["sub-type"] = metaAI_subtypes

In [46]:
AI_formal_val = [df_llm_essays, df_kimi_samples, df_metaAI_samples]

df_AI_formal_val = pd.concat(AI_formal_val, ignore_index=True)
df_AI_formal_val["AI_label"] = 1

df_AI_formal_val.to_csv("AI_formal_val_675.csv", index=False)

In [47]:
word_counts = df_AI_formal_val["sample_text"].apply(lambda t: len(t.split()))
print(word_counts.describe())

count    675.000000
mean     154.660741
std       64.281827
min       50.000000
25%       92.000000
50%      161.000000
75%      216.000000
max      250.000000
Name: sample_text, dtype: float64

## Full Set

In [58]:
human_formal_val = pd.read_csv(r"C:\Users\kacey\OneDrive - Simon Fraser University (1sfu)\IAT360\NLP Project\dataset\validation\human_formal_val_675.csv")
print(human_formal_val['sub-type'].value_counts())

AI_formal_val = pd.read_csv(r"C:\Users\kacey\OneDrive - Simon Fraser University (1sfu)\IAT360\NLP Project\dataset\validation\AI_formal_val_675.csv")
print(AI_formal_val['sub-type'].value_counts())

formal_val = pd.concat([human_formal_val, AI_formal_val], ignore_index=True)
formal_val.to_csv("formal_val_1350.csv", index=False)

formal_val

sub-type
letter        560
nonfiction     75
business       26
essay          14
Name: count, dtype: int64
sub-type
essay         405
business       92
nonfiction     90
letter         88
Name: count, dtype: int64

                                            sample_text    sub-type  AI_label
0     Even though lots of students like to work at h...      letter         0
1     Fresh air we're use to being home all day and ...  nonfiction         0
2     Many people believe that self-esteem comes fro...      letter         0
3     Clearly, everyone should always aim high and a...      letter         0
4     I really think that can be really stressed for...      letter         0
...                                                 ...         ...       ...
1345  Cryptography is the discipline concerned with ...  nonfiction         1
1346  Cultural anthropology investigates the diversi...  nonfiction         1
1347  The solar system consists of the Sun and the g...  nonfiction         1
1348  Public health is defined as the organized effo...  nonfiction         1
1349  The philosophy of language examines the relati...  nonfiction         1

[1350 rows x 3 columns]

In [59]:
word_counts = formal_val["sample_text"].apply(lambda t: len(t.split()))
print(word_counts.describe())

count    1350.000000
mean      196.757778
std        63.684916
min        48.000000
25%       157.000000
50%       228.000000
75%       248.000000
max       250.000000
Name: sample_text, dtype: float64

In [17]:
# 5400 train samples
train_path = r"C:\Users\kacey\OneDrive - Simon Fraser University (1sfu)\IAT360\NLP Project\dataset\formal_train_5400.csv"

# 1350 external val samples
val_path = r"C:\Users\kacey\OneDrive - Simon Fraser University (1sfu)\IAT360\NLP Project\dataset\formal_val_1350.csv"

formal_splits = {
    "train": train_path,
    "val": val_path
}

# Load as a dataset
full_dataset = load_dataset("csv", data_files=formal_splits)

full_dataset

DatasetDict({
    train: Dataset({
        features: ['sample_text', 'sub-type', 'AI_label'],
        num_rows: 5400
    })
    val: Dataset({
        features: ['sample_text', 'sub-type', 'AI_label'],
        num_rows: 1350
    })
})

## **Emergency Clean**

In [29]:
path = r"C:\Users\kacey\OneDrive - Simon Fraser University (1sfu)\IAT360\NLP Project\dataset\written_samples\human_articles_900.csv"
df = pd.read_csv(path)

word_counts = df["sample_text"].apply(lambda t: len(t.split()))
print(word_counts.describe())

count      900.000000
mean      1027.922222
std       1186.615377
min         40.000000
25%        475.000000
50%        748.000000
75%       1161.250000
max      17466.000000
Name: sample_text, dtype: float64

In [30]:
df["sample_text"] = df["sample_text"].apply(clean_CNN)

word_counts = df["sample_text"].apply(lambda t: len(t.split()))
print(word_counts.describe())

count    900.000000
mean     235.397778
std       17.694591
min       40.000000
25%      230.000000
50%      239.000000
75%      246.000000
max      250.000000
Name: sample_text, dtype: float64

In [34]:
df.to_csv("human_articles_900_cleaned.csv", index=False)

In [55]:
path = r"C:\Users\kacey\OneDrive - Simon Fraser University (1sfu)\IAT360\NLP Project\dataset\validation\human_formal_val_675.csv"
df = pd.read_csv(path)

word_counts = df["sample_text"].apply(lambda t: len(t.split()))
print(word_counts.describe())

count     675.000000
mean      440.346667
std       194.307188
min        48.000000
25%       294.500000
50%       406.000000
75%       542.000000
max      1170.000000
Name: sample_text, dtype: float64

In [56]:
df["sample_text"] = df["sample_text"].apply(clean_CNN)

word_counts = df["sample_text"].apply(lambda t: len(t.split()))
print(word_counts.describe())

count    675.000000
mean     238.854815
std       20.876341
min       48.000000
25%      237.000000
50%      248.000000
75%      250.000000
max      250.000000
Name: sample_text, dtype: float64

In [57]:
df.to_csv("human_formal_val_675_cleaned.csv", index=False)